### PR TITLE
Handle edge case where .rm lines have only one point (requiring 2)

### PR DESCRIPTION
**Pull request by Azeirah**
I encountered an edge case within one of my documents where `drawing.py` and `parsing.py` would crash because certain stroke segments contained only a single point.

This change at the very least prevents the crash, but I don't think I'm handling it correctly just yet.

When I convert the relevant page using the e-mail pdf functionality on my ReMarkable, I get this:

[Gosper.pdf](https://github.com/lucasrla/remarks/files/10923733/Gosper.pdf)

Using Remarks, it looks vastly different. It's hard to make out from this document what's going on, because remarks clearly displays an amount of strokes that the official software does not. (Could be the eraser?) Although that's a different problem.

(Note, this export comes from my local version of remarks, not from the most recent master branch in this repo)

[Gosper-remarks.pdf](https://github.com/lucasrla/remarks/files/10924046/Gosper-remarks.pdf)

I think the best course of action is to try and reproduce the problem from scratch. Simply putting down a bunch of dots and hope we reproduce it that way

### CODE REVIEW

**Comment by Azeirah** [comment]
Unfortunately I can only try and reproduce it on v3, not on v2 since my tablet is already updated to version 3.

I tried to reproduce it, and managed to do so. I put down a large amount of dots on the page.

This is the official PDF result

[dots.pdf](https://github.com/lucasrla/remarks/files/10924178/dots.pdf)

This is Remarks' result

[dots _remarks.pdf](https://github.com/lucasrla/remarks/files/10924186/dots._remarks.pdf)

Clearly the single-point "line segments" are not actually lines, but dots. We should not ignore them, but draw a dot instead.

**Comment by Azeirah** [comment]
Ok.. I'm not sure. I tried placing a very large amount of dots on a new document. Both ReMarkable's official software as well as Remarks render the document correctly without any exceptions.

I cannot seem to reproduce the original error where the points array had only one point in it, it might have been an issue with v2? Since the original document is a v2 document.

My idea is to skip the single-point "line segments" and print a warning whenever this does occur so we can investigate further if it ever pops up again.

**Comment by Azeirah** [comment]
I can attach the associated v2 notebook, since it is my own notebook without anything private in it. So I will add that test case in this PR as well

**Comment by Azeirah** [comment]
@lucasrla It's ready. I wasn't able to reproduce the exact issue, but I did add the original document where the remarks software would crash as a test.

Let me know if you have any comments

**Comment by lucasrla** [comment]
Not sure I follow what you meant by not being able to reproduce the issue. 

If I comment out the two continues, I do get a crash:

```sh
python -m remarks v2_notebook_complex/ v2_notebook_complex-out-$(date +"%Y%m%d_%H%M%S")/ --per_page_targets svg png md pdf --modified_pdf

  Found 1 documents in "v2_notebook_complex/", will process them now

  File: "Gosper.notebook" (bce041cf-ce31-4ede-ad11-2e53db0f6c77)
  ...
  shapely.errors.GEOSException: IllegalArgumentException: point array must contain 0 or >1 elements
```

For now, I believe that what you did (logging.warning and continue) is fine. I would just change the messaging to be more verbose but (in my opinion) clearer and more actionable:

```python
logging.warning("- Found a line segment with one or fewer lines, will ignore it. Please report this at https://github.com/lucasrla/remarks/pull/63")

logging.warning("- Found a line segment with only a single point, will ignore it. Please report this at https://github.com/lucasrla/remarks/pull/63")
```

**Comment by lucasrla** [comment]
> Using Remarks, it looks vastly different. It's hard to make out from this document what's going on, because remarks clearly displays an amount of strokes that the official software does not. (Could be the eraser?) Although that's a different problem.

It does look like an eraser there! I've never really tested the eraser tool thoroughly. So I won't be surprised at all that remarks has issues with it...

**Comment by Azeirah** [comment]
> ```python
> logging.warning("- Found a line segment with one or fewer lines, will ignore it. Please report this at https://github.com/lucasrla/remarks/pull/63")
> 
> logging.warning("- Found a line segment with only a single point, will ignore it. Please report this at https://github.com/lucasrla/remarks/pull/63")
> ```

Agreed, this would be more actionable.

For my own understanding, the lines consist of segments, right? So it should be worded the other way around?

> - Found a line with one or fewer line segments, will ignore it. Please ...

And not

> - Found a line segment with one or fewer lines, will ignore it. Please ...

**Comment by lucasrla** [comment]
I'd say that the parser "sees" just segments. I think introduced the concept of lines in order to take advantage of Shapely. As far I remember, lines were always created out of segments. 

But in terms of the text message, let's keep things simple for users:

```python
# drawing.py
logging.warning("- Found a segment with a single point, will ignore it. ...")

# parsing.py
logging.warning("- Found a segment with a single point, will ignore it. ...")
```

BTW, it just occurred to me, do you know if the two warnings are redundant? That is, their conditions are the same and they're always printed out together? If so, let's remove one of them.

Thanks

**Comment by lucasrla** [comment]
Sorry but I think I'm still missing something!

> I'm unable to reproduce the issue in v3 is what I meant.

By "in v3" you mean using the rmscene parser for v6 .rm lines created within reMarkable software >= 3.0?

**Comment by Azeirah** [comment]
The gosper file is made on ReMarkable software version v2.x.

v3 is my tablet's version, producing v6 .rm files. I get the confusion now :p

**Comment by lucasrla** [comment]
I just opened new issue to get a fresh URL for reports from users. We covered other topics here. 

I'd put https://github.com/lucasrla/remarks/issues/64 in the warning. 

Thanks again!

**Comment by Azeirah** [comment]
> BTW, it just occurred to me, do you know if the two warnings are redundant? That is, their conditions are the same and they're always printed out together? If so, let's remove one of them.

Yes, if the one in parser.py gets executed, the one in drawing.py gets executed as well.

afbeelding

Given the .rm-v5 gosper notebook (`v2_notebook_complex), it prints out a very large amount of warnings.

**Comment by Azeirah** [comment]
Prevented it. I think it's ready to merge

**Comment by Azeirah** [comment]
afbeelding

**Pull request merged**
