### PR TITLE
Fixing for the new highlights in rM v2.8 and 2.11. Refs #37 #39 #46 #47

### LINKED ISSUE #37: Upgrade to rM 2.8
In the last version of the rM software, they added a functionality where they will attempt to adjust your hand highlights to the text. So if the pdf has text (not an image of text), it will "reformat" the highlight to be a block over the text.

The highlight extraction for this no longer works in remarks. I tested this by making a malformatted highlight on a pdf (one that rM would not "refactor") and it shows up just fine after remarks in the annotated pdf. But the highlights that rM "refactors" do not show up. 

I tried to look through the `parse_rm_file` function, but I could not easily see what the problem would be without digging into the rM output to see how the new highlights are stored. 

Any chance for an update?

### PR DESCRIPTION
**Pull request by folofjc**
My attempt to fix #37. I wrote a lot of comments so that you could see what I was doing. Feel free to re-factor, etc.

I tested it locally and it works great! I tested with the "old" annotations from pens as well as highlighter that did not get "modified". (i.e. I highlighted in the margins, etc, where there was no text).

### CODE REVIEW

**Comment by folofjc** [comment]
I just pushed again to my master with the fixes for #39. I think you can still use the same PR, right?

**Comment by folofjc** [comment]
Added support for #46 and #47

**Comment by lucasrla** [comment]
@folofjc, thank you so much for taking the time to submit all these improvements. I'll resolve the many conflicts and merge them during the weekend.

Meanwhile, you probably want to take a look at the various changes that I've just pushed.

Thanks again!

**Comment by lucasrla** [comment]
Your PR is now merged.

I left the highlighting parts out of the merge (given that I had followed a different path to support smart highlights). I also tweaked a bit of flags names / logic.

Thanks again!

**Comment by folofjc** [comment]
Okay, great, thanks for incorporating all this! I will do a pull into mine, and it should bring in all the changes.

**Pull request merged**
